# Generated by Django 4.2.6 on 2023-11-22 09:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_purchased', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 14, 32, 43, 33613))),
                ('current_coin_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='List_Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=64, unique=True)),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_list', models.ManyToManyField(blank=True, related_name='watchers', to='exchange.coin')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.ManyToManyField(blank=True, related_name='containing_wallets', to='exchange.coin')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_on', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 14, 32, 43, 33613))),
                ('transacted_coin_value', models.FloatField()),
                ('transacted_amount', models.FloatField(default=0)),
                ('buyer_receier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to=settings.AUTH_USER_MODEL)),
                ('seller_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to=settings.AUTH_USER_MODEL)),
                ('transacted_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacted', to='exchange.list_coin')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='exchange.list_coin'),
        ),
    ]
