# Generated by Django 4.2.6 on 2023-11-23 16:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_coin_last_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='last_purchased',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 50, 22, 430273)),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 50, 22, 430273)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='exchange.list_coin'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_coin_no', models.FloatField()),
                ('order_amount_per_coin', models.FloatField()),
                ('order_amount', models.FloatField(default=0)),
                ('is_buy', models.BooleanField(default=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('fulfill_time', models.DateTimeField(blank=True)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('order_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed', to='exchange.list_coin')),
            ],
        ),
    ]
