# Generated by Django 4.2.6 on 2023-11-23 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_coin_last_purchased_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_amount_per_coin',
            new_name='order_price_per_coin',
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_purchased',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 58, 41, 529282)),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 58, 41, 544905)),
        ),
    ]
