# Generated by Django 4.2.6 on 2023-11-23 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_coin_last_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_purchased',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 22, 54, 8, 946114)),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 22, 54, 8, 946114)),
        ),
    ]
