# Generated by Django 4.2.6 on 2023-11-23 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_alter_coin_last_purchased_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='fulfill_time',
            new_name='fulfilled_on',
        ),
        migrations.AddField(
            model_name='orders',
            name='closed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_purchased',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 23, 15, 33, 7042)),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 23, 15, 33, 9042)),
        ),
    ]
