# Generated by Django 4.2.6 on 2023-11-24 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_alter_coin_last_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='transact_action',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_purchased',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 22, 11, 1, 817030)),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 22, 11, 1, 817030)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 22, 11, 1, 817030)),
        ),
    ]
