# Generated by Django 4.2.6 on 2023-11-24 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0020_alter_coin_last_purchased_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='seller_sender',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='buyer_receiver',
            new_name='to_user',
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_purchased',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 22, 29, 59, 538830)),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 22, 29, 59, 538830)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 22, 29, 59, 538830)),
        ),
    ]
