# Generated by Django 4.2.6 on 2023-11-24 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_rename_seller_sender_history_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='last_purchased',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 22, 30, 20, 218885)),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 22, 30, 20, 218885)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 22, 30, 20, 218885)),
        ),
    ]
