# Generated by Django 4.2.6 on 2023-11-28 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0025_user_profile_url_alter_coin_last_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='last_purchased',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 10, 49, 573433)),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 10, 49, 575432)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 10, 49, 575432)),
        ),
    ]
